Dev/more clippy
algesten/str0m pull request #17
Opened 2022-12-29 01:18 UTC by xnorpx

make clippy happy

2022-12-29 04:01 UTC, algesten requested changes
Looks good, thanks! One thing to discuss.

2022-12-29 04:10 UTC, xnorpx commented on rtp/src/rtcp/sdes.rs
> +                *val = SdesType::END as u8;
yeah, I wasn't sure about it either. I agree it loses readability. You might add safety as the iterator might do bounds checking. Will disable the lint on these

2022-12-29 04:14 UTC, algesten commented on rtp/src/rtcp/sdes.rs
> +                *val = SdesType::END as u8;
Thanks!

2022-12-29 21:22 UTC, algesten requested changes

2022-12-29 21:22 UTC, algesten commented on ice/src/pair.rs
> +        2_u64.pow(32) * g.min(d) as u64 + 2 * g.max(d) as u64 + u64::from(g > d)
let's not change this

2022-12-29 21:22 UTC, algesten commented on ice/src/agent.rs
> +            x - u32::from(!ip.is_ipv6())
let's not change this

2023-01-01 12:00 UTC, algesten commented
This is in main now.

2023-01-01 12:00 UTC, closed without merging