Handle different RTX availability among answering sendonly mlines
algesten/str0m pull request #345
Opened 2023-09-11 13:30 UTC by david-flok

I'm relatively new to rust, WebRTC, and str0m so please forgive me if my thinking is wrong. I really appreciate any advice you might have.

I am prototyping a new streaming solution using str0m and I found that when a browser client generates a recvonly SDP 'offer' for audio and video streams, str0m will answer both the video and the audio mlines with multiple ssrcs even when only the video mline has any payload types with RTX available. This then causes an error like

```
[28394:25603:0911/135240.480561:ERROR:sdp_offer_answer.cc(911)] Failed to set remote answer sdp: Failed to add remote stream ssrc: 1990811668 to {mid: 1, media_type: audio}
```

in Safari and Chrome (both are libwebrtc users? probably rejected by others?) as they have an SDP answer validation routine that checks for the presence of exactly one ssrc for audio streams.

I've now changed the computation for RTX availability in the SDP response to take into account only those payloads for the current media stream under consideration for ssrc addition. To my eye, this seems to indicate that the type design for sessions/codec config/media descriptions is incorrect as I'd expect the data structure to have already indexed codec config under media streams such that this bug would be impossible. As I said, I'm relatively new to all of these technologies so I'd be very grateful for an explanation why this is or isn't the case.

I suppose that another solution would be to set up some session parameters manually during the negotiation to suppress this SDP response or munge the answer after generation but both of these seems less satisfactory than preventing the default str0m behaviour from being rejected by clients.

Please let me know if you'd like tests or documentation or discussion via zulip or anything else before merging (if the change is acceptable).

Thanks!

2023-09-11 17:36 UTC, algesten commented
Hi @david-flok and welcome to str0m!

Thanks for the PR. I'm trying to get my head around the problem. One thing to note that `p.resend().is_some()` should in theory be enough since we don't do resends without RTX (we don't support resends on the "main" ssrc).

Could you copy the initial SDP OFFER from your browser that results in this error?

2023-09-12 08:35 UTC, david-flok commented
Hi, @algesten! Sorry I missed out a lot of the normal bug report info.

The browser offers something like:

```
v=0
o=- 2198475125021156817 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 35 36 37 38 102 103 104 105 106 107 108 109 127 125 39 40 41 42 43 44 45 46 47 48 112 113 114 115 116 117 118 49
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:vetN
a=ice-pwd:ucIaYhVOmBZOh6z5beOmkkZH
a=ice-options:trickle
a=fingerprint:sha-256 33:56:A4:08:DB:16:46:51:33:DB:0E:E2:57:18:9E:30:9F:F7:31:21:2C:DF:3A:88:4C:72:30:48:A4:84:1C:CE
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 urn:3gpp:video-orientation
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:35 VP9/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=fmtp:35 profile-id=1
a=rtpmap:36 rtx/90000
a=fmtp:36 apt=35
a=rtpmap:37 VP9/90000
a=rtcp-fb:37 goog-remb
a=rtcp-fb:37 transport-cc
a=rtcp-fb:37 ccm fir
a=rtcp-fb:37 nack
a=rtcp-fb:37 nack pli
a=fmtp:37 profile-id=3
a=rtpmap:38 rtx/90000
a=fmtp:38 apt=37
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:103 rtx/90000
a=fmtp:103 apt=102
a=rtpmap:104 H264/90000
a=rtcp-fb:104 goog-remb
a=rtcp-fb:104 transport-cc
a=rtcp-fb:104 ccm fir
a=rtcp-fb:104 nack
a=rtcp-fb:104 nack pli
a=fmtp:104 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:105 rtx/90000
a=fmtp:105 apt=104
a=rtpmap:106 H264/90000
a=rtcp-fb:106 goog-remb
a=rtcp-fb:106 transport-cc
a=rtcp-fb:106 ccm fir
a=rtcp-fb:106 nack
a=rtcp-fb:106 nack pli
a=fmtp:106 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=106
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d001f
a=rtpmap:125 rtx/90000
a=fmtp:125 apt=127
a=rtpmap:39 H264/90000
a=rtcp-fb:39 goog-remb
a=rtcp-fb:39 transport-cc
a=rtcp-fb:39 ccm fir
a=rtcp-fb:39 nack
a=rtcp-fb:39 nack pli
a=fmtp:39 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=4d001f
a=rtpmap:40 rtx/90000
a=fmtp:40 apt=39
a=rtpmap:41 H264/90000
a=rtcp-fb:41 goog-remb
a=rtcp-fb:41 transport-cc
a=rtcp-fb:41 ccm fir
a=rtcp-fb:41 nack
a=rtcp-fb:41 nack pli
a=fmtp:41 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=f4001f
a=rtpmap:42 rtx/90000
a=fmtp:42 apt=41
a=rtpmap:43 H264/90000
a=rtcp-fb:43 goog-remb
a=rtcp-fb:43 transport-cc
a=rtcp-fb:43 ccm fir
a=rtcp-fb:43 nack
a=rtcp-fb:43 nack pli
a=fmtp:43 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=f4001f
a=rtpmap:44 rtx/90000
a=fmtp:44 apt=43
a=rtpmap:45 AV1/90000
a=rtcp-fb:45 goog-remb
a=rtcp-fb:45 transport-cc
a=rtcp-fb:45 ccm fir
a=rtcp-fb:45 nack
a=rtcp-fb:45 nack pli
a=rtpmap:46 rtx/90000
a=fmtp:46 apt=45
a=rtpmap:47 AV1/90000
a=rtcp-fb:47 goog-remb
a=rtcp-fb:47 transport-cc
a=rtcp-fb:47 ccm fir
a=rtcp-fb:47 nack
a=rtcp-fb:47 nack pli
a=fmtp:47 profile=1
a=rtpmap:48 rtx/90000
a=fmtp:48 apt=47
a=rtpmap:112 H264/90000
a=rtcp-fb:112 goog-remb
a=rtcp-fb:112 transport-cc
a=rtcp-fb:112 ccm fir
a=rtcp-fb:112 nack
a=rtcp-fb:112 nack pli
a=fmtp:112 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f
a=rtpmap:113 rtx/90000
a=fmtp:113 apt=112
a=rtpmap:114 H264/90000
a=rtcp-fb:114 goog-remb
a=rtcp-fb:114 transport-cc
a=rtcp-fb:114 ccm fir
a=rtcp-fb:114 nack
a=rtcp-fb:114 nack pli
a=fmtp:114 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=64001f
a=rtpmap:115 rtx/90000
a=fmtp:115 apt=114
a=rtpmap:116 red/90000
a=rtpmap:117 rtx/90000
a=fmtp:117 apt=116
a=rtpmap:118 ulpfec/90000
a=rtpmap:49 flexfec-03/90000
a=rtcp-fb:49 goog-remb
a=rtcp-fb:49 transport-cc
a=fmtp:49 repair-window=10000000
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 0 8 13 110 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:vetN
a=ice-pwd:ucIaYhVOmBZOh6z5beOmkkZH
a=ice-options:trickle
a=fingerprint:sha-256 33:56:A4:08:DB:16:46:51:33:DB:0E:E2:57:18:9E:30:9F:F7:31:21:2C:DF:3A:88:4C:72:30:48:A4:84:1C:CE
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:126 telephone-event/8000
```

and after I use str0m like this

```rust
    rtc.add_local_candidate(candidate);
    let offer = SdpOffer::from_sdp_string(&sdp_offer).unwrap();
    let answer = rtc.sdp_api().accept_offer(offer).unwrap();
```

my prototype responds with

```
v=0
o=str0m-0.2.0 656678899277619955 2 IN IP4 0.0.0.0
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS AGXahTQxSSvQHl7Bb8CVPq94IAFoae RhPRU2H7RKQbG63z8PEL2hHCQA9aDl
m=video 9 UDP/TLS/RTP/SAVPF 96 97 102 103 104 105 106 107 108 109 127 125 39 40 112 113 98 99 100 101
c=IN IP4 0.0.0.0
a=candidate:10132957947938846246 1 udp 2130706175 192.168.1.16 52935 typ host ufrag CbnC
a=ice-ufrag:CbnC
a=ice-pwd:86UvUPlre61qivrqUYgVMQ
a=ice-options:trickle
a=fingerprint:sha-256 A2:E6:D8:76:C3:80:01:15:17:61:4C:B5:6C:11:4F:96:51:98:6A:34:82:BC:95:BA:05:B8:17:CA:35:D4:FE:13
a=setup:passive
a=mid:0
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 urn:3gpp:video-orientation
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendonly
a=msid:AGXahTQxSSvQHl7Bb8CVPq94IAFoae nUbXR6TAltjHzzKER0h5Avr5vk609e
a=rtcp-mux
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:102 H264/90000
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id [...]

2023-09-12 08:51 UTC, david-flok commented
I've updated the patch according to `cargo fmt` now.

2023-09-12 08:54 UTC, algesten commented
Thanks for the additional information! And I agree your fix is correct.

> Naively, it seems to me that codec configuration for payload types should belong to streams rather than sessions as a whole.

Thing is that payload type mappings belong on the session level (well, "BUNDLE" level if we are pedantic). That means we can't have PT=96 meaning one thing in Media (m-line) MID=0 and another in MID=1. Hence once the remote negotiates a specific mapping for a PT, it's locked down on session level.

2023-09-12 08:56 UTC, algesten requested changes
One little thing.

Also, can you add one more line break between the headline and the body here to make git log format it well:

```
    SDP: RTX allowability is per media
    When multiple media streams are present, multiple ssrcs should only be generated
    ...
```

2023-09-12 08:56 UTC, algesten commented on src/change/sdp.rs
> +            .any(|p| p.resend().is_some() && media.remote_pts().contains(&p.pt));
Can you change this so that the `media.remote_pts()` check comes in a `.filter` before the `.any`?

2023-09-12 09:02 UTC, algesten approved these changes
Let's merge!

Thanks!

2023-09-12 09:06 UTC, algesten commented
This is in main now. I edited the git log comment and merged manually.

2023-09-12 09:06 UTC, closed without merging

2023-09-12 09:08 UTC, david-flok commented
Right, the payload type identifier space is shared across the entirety of the SDP, iiuc. Also, as I understand it, this invariant is not maintained by a type (e.g. a table or some kind of map from PT to codec config). Just because the spec has a big namespace doesn't mean that str0m has to adhere to that for its internal representation, right? It seems presently a 'join' to required for 'querying' this information but Media -> PT is a one-to-many relationship...

Thanks for merging and sorry to keep on about this. I'm trying to understand the rationale for the type design (and learning about the SDP data model).

2023-09-12 09:14 UTC, algesten commented
> Right, the payload type identifier space is shared across the entirety of the SDP, iiuc. 

Correct.

> Also, as I understand it, this invariant is not maintained by a type (e.g. a table or some kind of map from PT to codec config).

The PT is 7 bit, so 127 max. There are a number of "well known" preallocated PT that comes from back in the day when RTP was new. However times move on, and there are many codecs these days, hence the exact PT - codec allocation is negotiated via SDP.

>  Just because the spec has a big namespace doesn't mean that str0m has to adhere to that for its internal representation, right? It seems presently a 'join' to required for 'querying' this information but Media -> PT is a one-to-many relationship…

The only time we need to match up PT with the codec definition is during SDP negotiation, which means it's a rather rare operation (not hot path). There are also cases where we need to fuzzy match the remote codec definition with PT and of course we could iterate a map, there is not really an advantage. Hence it's a `Vec` in session.

(I'm also slightly partial to lists rather than having maps everywhere)

2023-09-12 09:21 UTC, david-flok commented
Thanks, that's helpful!

So it seems that the session wide PT id 'namespace' invariant isn't really that important for the state machine but the question of 'what are the codec configurations that correspond to this media stream?' is likely to be frequently asked after negotiation. Could the codec configuration be moved into `Media`?

`Media` already seems to be demanding some invariants that could be lifted into its type:

```rust

    /// Remote PTs negotiated for this media.
    ///
    /// This tells us both the desired priority order of payload types
    /// as well as which PT the remote side wants (in case they are narrowed).
    ///
    /// These must have corresponding entries in Session::codec_config.
    ///
    /// SDP property.
    remote_pts: Vec<Pt>,

    /// Remote extmaps negotiated for this media.
    ///
    /// The corresponding entries must exist in Session::codec_config.
    ///
    /// These are 1-indexed to be exactly like in the SDP.
    remote_exts: ExtensionMap,
```

2023-09-12 11:22 UTC, algesten commented
> the question of 'what are the codec configurations that correspond to this media stream?' is likely to be frequently asked after negotiation.

It actually isn't, or at least, doesn't need to be. Once codec configurations and their PT mappings are negotiated, the RTP layer just says "this is a packet with PT 96" – what that actually means codec wise is technically not interesting for transporting the data.

There are of course exceptions.

1. Temporal layers. VP8 and other codecs have temporal layers, which means there are frames (roughly RTP packets, but can be more than one), that can be dropped and the video decoding works anyway. That means we could avoid making and responding to NACKs that we know are not necessary.
2. str0m tries to be helpful and translate RTP time (u32) into `MediaTime`, which has the clock frequency. We solve that by caching enough information in `StreamRx` to avoid needing the full codec specification on every packet: https://github.com/algesten/str0m/blob/main/src/streams/receive.rs#L55

> Could the codec configuration be moved into Media?

Not very long ago, that's where it was. However again, like with the PT mapping, the actual configuration can't differ between `Media` for a PT. `a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f` means PT 96 needs this config, in every `Media`. 

This is actually more of an SDP problem that it _looks like_ we can have different PT/specs per codec per m-line, but that's not actually the case. The configuration is for the session (BUNDLE), and which PTs are used is per `Media` (m-line).

On balance, I think the current structure for this is correct.

2023-09-12 12:45 UTC, david-flok commented
Ahhh... I understand now, thank you! The `Media` <-> PT relationship *isn't* one-to-many, it really is many-to-many even if usually there is only a single `Media` using a PT and even if the PT details are under the m-lines. I guess it's a validation error if the PT is reused with different parameters in another m-line?

Sorry to bother you and thanks again for the explanation. For my application, I'm not proxying streams like an SFU, I'm either generating them or reading them out of media container formats so I envisioned referring to codec configurations at streamtime to determine which PT to send on and with what configuration but perhaps I should cache the mapping or don't need that dynamism -- I'm not quite to the stage of development where I need to do those determinations, yet.

Thanks!

2023-09-12 13:02 UTC, algesten commented
> Ahhh... I understand now, thank you! The Media <-> PT relationship isn't one-to-many, it really is many-to-many 

Yes. It's perfectly OK to send some media for the same m-line with PT for VP8 and then suddenly switch to another PT for H264 if that was negotiated. I never seen it in the wild, but it could/should work.

> even if usually there is only a single Media using a PT and even if the PT details are under the m-lines.

Quite common to have many with the same. Think video conference with many incoming cameras. Different m-lines, same video PTs.

> I guess it's a validation error if the PT is reused with different parameters in another m-line?

Yes. That should fail. Unclear if str0m is enforcing it.