Add contiguity check for VP9 codec
algesten/str0m pull request #433
Opened 2024-01-04 17:12 UTC by h1t

Check frame contiguity for VP9 codec in non-flexible mode.
Just copy/paste from VP8 contiguity implementation.
Refactored code duplication.

2024-01-04 18:10 UTC, algesten requested changes
Hi @h1t, welcome to str0m!

This looks great! I had one little question about the code structure.

About the `contiguous_vp9.pcap`, is it not possible to reuse the `vp9.pcap` for this test? If not, I think we should at least make a `contiguous_vp9.txt` similar to the other files. It's an export of the text form using wireshark.

2024-01-04 18:10 UTC, algesten commented on src/packet/vp8_contiguity.rs
> +pub(crate) struct FrameContiguityState {
Should we maybe move `FrameContiguityState` to packet/contiguity.rs since it's shared for both vp8 and vp9?

2024-01-04 18:13 UTC, algesten commented
Also, @davibe I know you're on holiday, but your input here would be very appreciated since the previous code was your baby.

2024-01-07 11:47 UTC, davibe commented
@algesten I got no objections :)

For context the reason we needed the contiguity check for VP8 is because with network loss Safari (stable) deliberately avoids retransmitting frames that "can be skipped" (no other frame depends on them). In reality sometimes it also avoids retransmitting frames that are needed. The contiguity checks reduces the amount of discontinuities str0m detects and reports in MediaData (which normally results in a keyframe request) and the amount of times our buffer 'holds back' waiting for them (jitter). Ever since we fixed the nack-logic, I no longer think other browser share this behaviour.

Also, Testing Safari Technology preview I have seen it behave "correctly" as other browsers. This is why I thought of this contiguity thing as a mitigation which I hoped to remove when Safari "got fixed". 

I have no data on the behaviour of the different browsers when using VP9.

2024-01-07 14:21 UTC, merged