feat: expose `Candidate::discarded`
algesten/str0m pull request #497
Opened 2024-04-17 02:23 UTC by thomaseizinger

This is useful / necessary to differentiate between active and invalidated candidates when accessing them via `IceAgent::local_candidates`.

Alternatively, we could also filter them directly there or prune all discarded candidates from the agent?

2024-04-18 14:07 UTC, algesten requested changes
Could we filter them instead?

As I see it, `Candidate` should not have a state. The discarded flag is probably there or convenience, but we don't want it. Especially not in public API.

2024-04-18 22:46 UTC, thomaseizinger commented
> Could we filter them instead?
> 
> As I see it, `Candidate` should not have a state. The discarded flag is probably there or convenience, but we don't want it. Especially not in public API.

Yeah definitely. So `local_candidates` and `remote_candidates` always filtered by `!discarded`?

Shall we move them to a different collection perhaps so we can remove the state?

2024-04-19 03:15 UTC, algesten commented
I think because we use usize indexes to the vec holding them, we can't move them out easily. We could make some wrapper Entry type to hold the state and candidate though.

2024-04-19 03:43 UTC, thomaseizinger commented
> I think because we use usize indexes to the vec holding them, we can't move them out easily. We could make some wrapper Entry type to hold the state and candidate though.

Hmm, right. Perhaps a [`slab`](https://docs.rs/slab/latest/slab/) would help here?

2024-08-09 03:47 UTC, closed without merging