Support getting stream_id and track_id of Media
algesten/str0m pull request #550
Opened 2024-07-27 15:43 UTC by uwuPyxl

Get the stream_id and track_id from the incoming MediaLine and expose them to users on the resulting Media so they can tell incoming Media apart. Should the incoming Media not have a Msid attribute this falls back to the previous behavior of generating random ids

2024-07-28 07:22 UTC, algesten commented
Hey! Thanks for this!

I was under the impression that msid was deprecated, but I think I'm mistaken. The `a=ssrc` lines are not in fashion anymore, which means getting msid there is not a good idea. But this PR is working with `a=msid`, which seems to still be good API. Is that your understanding too?

2024-07-28 11:37 UTC, uwuPyxl commented
I just used the msid attribute since it was most obvious and convenient but yeah it does seem to be intended for this purpose.

2024-08-02 08:44 UTC, algesten commented on src/media/mod.rs
> +    /// Identifier for this Media. Should be unique for the given stream id.
Line break here

2024-08-02 08:45 UTC, algesten requested changes
Ok. Let's merge, but 3 small formatting things first.

2024-08-02 08:45 UTC, algesten commented on src/media/mod.rs
> +    }
New line here.

2024-08-02 08:45 UTC, algesten commented on src/sdp/data.rs
> +    pub fn msid(&self) -> Option<Msid> {
New line here.

2024-08-02 08:45 UTC, algesten commented on src/sdp/data.rs
> +impl Msid {
New line here.

2024-08-02 12:18 UTC, uwuPyxl commented
I've updated the formatting manually, but it should be possible to set up a rustfmt.toml to configure the formatting rules

2024-08-03 15:03 UTC, algesten approved these changes

2024-08-03 15:04 UTC, merged