fix: ensure lexical ordering of SDP-formatted candidates follows priority
algesten/str0m pull request #557
Opened 2024-08-07 09:14 UTC by thomaseizinger

Fixes: #556.

2024-08-07 09:22 UTC, lolgesten requested changes

2024-08-07 09:22 UTC, lolgesten commented on src/ice/candidate.rs
> +        format!("{:x}{hash:x}", self.prio().to_be())
I think you need to pad with 0 or you get:

* 10000
* ff

2024-08-09 10:23 UTC, thomaseizinger commented
I think the priorities that we generate are always already taking the full range but I added the padding anyway :)

2024-08-09 11:18 UTC, lolgesten approved these changes

2024-08-09 11:19 UTC, algesten approved these changes

2024-08-09 11:19 UTC, merged