chore: add warning log when exceeding max number of pairs
algesten/str0m pull request #587
Opened 2024-11-13 22:06 UTC by thomaseizinger

We've recently had a bug in Firezone where we generated a lot of unnecessary server-reflexive candidates. This was only caught by chance due to a different bug report from a user.

We do have automated reporting set up whenever parts of our code emit `WARN` and `ERROR` logs. Adding a WARN log here allows this automated reporting to kick in if that should happen again.

I think - in general - adding a WARN log here is justified. Exceeding the max number of candidates can technically lead to connectivity problems so informing the user about this via a WARN log seems good.

2024-11-14 08:03 UTC, algesten commented
@thomaseizinger looks good.

Won't this give you a false positive for long lived road warriors? Like someone having a laptop over 5G on a train.

2024-11-14 14:01 UTC, algesten requested changes
Let's land it, but with a change to ensure it only logs once.

2024-11-14 20:34 UTC, thomaseizinger commented
> Let's land it, but with a change to ensure it only logs once.

Once per what? This happens before the loop so only once per removal of overflow candidates.

Do you also want it to not log when we repeatedly add more candidates after that?

2024-11-15 12:20 UTC, algesten commented
That's it. Our instances can live for very long. So once per instance of the ice agent.

2024-11-16 10:17 UTC, thomaseizinger commented
> That's it. Our instances can live for very long. So once per instance of the ice agent.

Done. I added a flag that prevents this from logging repeatedly. The flag is reset on `ice_restart` and when the limit gets changed.

2024-11-16 16:51 UTC, merged