Expose CandidateKind
algesten/str0m pull request #79
Opened 2023-03-03 20:14 UTC by morajabi

2023-03-03 22:50 UTC, algesten approved these changes

2023-03-13 15:37 UTC, algesten commented
Hey @morajabi!

Maybe we should rename this PR? I think we can merge. Server reflexive looks ok to me.

2023-03-14 22:17 UTC, algesten commented
Just a little lint fix. Looks trivial.

2023-06-21 06:34 UTC, algesten commented
Hey @morajabi do you want to land this one?

2023-06-21 06:34 UTC, algesten requested changes

2023-06-21 06:34 UTC, algesten commented on ice/src/candidate.rs
> +    pub fn new(
This should not be public.

2023-10-13 14:01 UTC, morajabi commented
@algesten Sorry this took this long. Applied changes you requested. Please let me know what you think 🙏
(P.S. str0m has made HUGE progress, thanks to all of you, we're happily using str0m in production for months in our desktop app for P2P usecase)

2023-10-13 16:27 UTC, algesten requested changes
Looks good!

Just some lint error then we land it!

2023-10-13 16:27 UTC, algesten commented on src/ice/candidate.rs
> +    /// Server reflexive candidates are local sockets mapped to external ip discovered via a STUN binding request.
Break this line up around ~100 ish line length, please.

2023-10-13 16:27 UTC, algesten commented on src/ice/candidate.rs
> +    /// Relayed candidates are server sockets relaying traffic to a local socket. Allocate a TURN addr to use as a local candidate.
Ditto

2023-10-14 15:31 UTC, algesten approved these changes

2023-10-14 15:41 UTC, merged